version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map port 8000 on the host to port 8000 in the container
      - "5100:5100" # 5100 is used for pixlet serve interface during app configuration
      - "5101:5101" # user 2
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # used to sync docker with host time
#      - .:/app # remove when ready for production
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - SERVER_PORT=${SERVER_PORT}
      - PYTHONUNBUFFERED=1
      