#!/bin/bash
set -euo pipefail

if [ "${PRODUCTION:-1}" = "1" ]; then
    # PRODUCTION
    exec granian --interface asgi --host 0.0.0.0 --port 8000 "tronbyt_server:application"
else
    # DEVELOPMENT
    FLASK_APP=tronbyt_server FLASK_DEBUG=1 exec flask run --host=0.0.0.0 --port=8000
fi