name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py312
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py312
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests --doctest-modules --junitxml=junit/test-results.xml
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile